### ISSUE TITLE
3d images

### ISSUE THREAD

**Issue by czainab** [deeplizard/Keras-Machine-Learning-Deep-Learning-Tutorial#5]
Hi @deeplizard  I want to know that is it possible to use 3d data instead of 2d for vgg model. How can one apply these models on 3d images

**Comment by deeplizard** [comment]
Hey @czainab, I've not worked with 3D images using Keras myself, but it appears that Keras' ImageDataGenerator() is not equipped to deal with 3D images, as discussed in the link below:
https://github.com/keras-team/keras/issues/2939
