### ISSUE TITLE
Moving codes to different website 

### ISSUE THREAD

**Issue by aalzooke** [deeplizard/Keras-Machine-Learning-Deep-Learning-Tutorial#7]
you can please keep posting your code on GitHub. I don't like the new website where you post all of your code. 
Thank you

**Comment by deeplizard** [comment]
Hey @aalzooke - Currently, the code files are publicly available on the new website, but soon, access to download the code files will only be available as a perk for the deeplizard hivemind. Check out the details regarding deeplizard perks and rewards at: http://deeplizard.com/hivemind
